=== KWABENA81/autoservice-app/inputdata.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT inputdata (appdata, properties, file_storage*, countryInfo, defn, defaults )>
<!ELEMENT appdata (author)>
	<!ELEMENT author (name, contact,title, revdate)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT contact (#PCDATA)>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT revdate (#PCDATA)> 
<!ELEMENT properties (company)>
	<!ELEMENT company (outlet, busnr, address+, city, provstate?, postalcode?, country, phone+, fax?, companyEmail?, webpage?, personnel+, labourrate+)> 
		<!ELEMENT outlet (#PCDATA)>
		<!ELEMENT busnr (#PCDATA)>
		<!ELEMENT address (#PCDATA)> 
		<!ELEMENT city (#PCDATA)>
		<!ELEMENT provstate (#PCDATA)>
		<!ELEMENT postalcode (#PCDATA)>
		<!ELEMENT country (#PCDATA)>
		<!ELEMENT phone (#PCDATA)>
		<!ELEMENT fax (#PCDATA)>
		<!ELEMENT companyEmail (#PCDATA)>
		<!ELEMENT webpage (#PCDATA)>
		<!ELEMENT personnel (mgr+, employee*)>
		<!ELEMENT mgr (#PCDATA)> 
		<!ELEMENT employee (#PCDATA)> 
		<!ELEMENT labourrate (regular, special, extra)>
			<!ELEMENT regular (#PCDATA)>
			<!ELEMENT special (#PCDATA)>
			<!ELEMENT extra (#PCDATA)>
<!ELEMENT file_storage (ftype, path)>
	<!ELEMENT ftype (#PCDATA)>
	<!ELEMENT path (#PCDATA)>
<!ELEMENT countryInfo (countryName+, mailCodeEnforced, mailCodeFormat*)>
	<!ELEMENT countryName (#PCDATA)> 
	<!ELEMENT mailCodeEnforced (#PCDATA)>
	<!ELEMENT mailCodeFormat (#PCDATA)>
<!ELEMENT definedformats (email+)>
	<!ELEMENT email (#PCDATA)> 
<!ELEMENT defaults (yearsLimit?, taxRate+, invoice_output_path?, partnumber*, jobIDLength, platePrefix, defaultuser)>
	<!ELEMENT yearsLimit (#PCDATA)>
	<!ELEMENT taxRate (#PCDATA)>
	<!ELEMENT invoice_output_path (#PCDATA)>
	<!ELEMENT partnumber (#PCDATA)>
	<!ELEMENT jobIDLength (#PCDATA)>
	<!ELEMENT platePrefix (#PCDATA)>
	<!ELEMENT defaultuser (firstname, lastname, phone, address)>
		<!ELEMENT firstname (#PCDATA)>
		<!ELEMENT lastname (#PCDATA)>
		<!ELEMENT phone (#PCDATA)>
		<!ELEMENT address (street, city, mailcode, region, country)>
			<!ELEMENT street (#PCDATA)>
			<!ELEMENT city (#PCDATA)>
			<!ELEMENT mailcode (#PCDATA)>
			<!ELEMENT region (#PCDATA)>
			<!ELEMENT country (#PCDATA)>

=== KWABENA81/autoservice-app/inputdata.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE toc SYSTEM "inputdata.dtd">
<inputdata>
	<appdata>
		<author>
			<name>Solomon SA</name>
			<contact>Toronto, Ontario</contact>
			<title>Auto Service Application</title>
			<revdate>February 29th, 2016</revdate>
		</author>
	</appdata>
	<properties>
		<company>
			<outlet>ASKSEF Auto Centre</outlet>
			<busnr>125-456-9874</busnr>
			<address>225 Samcy Road</address>
			<address>Plot #234</address>
			<city>Shantt City</city>
			<provstate>Shantt City</provstate>
			<postalcode>Shantt City</postalcode>
			<country>01224567895</country>
			<phone>99999999</phone>
			<fax>099999999</fax>
			<companyEmail>099999999</companyEmail>
			<webpage>099999999</webpage>
			<personnel>
				<mgr>ASKSEF</mgr>
				<employee>SASK</employee>
			</personnel>
			<labourrate>
				<regular>90.00</regular>
				<special>75.00</special>
				<extra>50.00</extra>
			</labourrate>
		</company>
	</properties>
	<file_storage>
		<ftype>reports</ftype>
		<path>C:\Users\sasefa\workspace3\reports</path>
	</file_storage>
	<file_storage>
		<ftype>invoices</ftype>
		<path>C:\Users\sasefa\workspace3\invoices</path>
	</file_storage>
	<countryInfo>
		<countryName>CANADA</countryName>
		<mailCodeEnforced>TRUE</mailCodeEnforced>
		<mailCodeFormat>([A-Za-z][0-9][A-Za-z]){1}([0-9][A-Za-z][0-9]){1}</mailCodeFormat>
	</countryInfo>
	<definedformats>
		<email>^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$</email>
	</definedformats>
	<defaults>
		<yearsLimit>25</yearsLimit>
		<taxRate>8</taxRate>
		<taxRate>5</taxRate>
		<taxRate>0</taxRate>
		<taxRate>0</taxRate>
		<invoice_output_path>C:\Users\SASEFA\Documents\invoices</invoice_output_path>
		<partnumber>GEN99999</partnumber> 
		<jobIDLength>7</jobIDLength>
		<platePrefix>NP_</platePrefix>
		<defaultuser>
			<firstname>ASKSEF</firstname>
			<lastname>ASKSEF</lastname>
			<phone>9999999</phone>
			<address>
				<street>Dummy Street</street>
				<city>Pit City</city>
				<mailcode>D9M4M8</mailcode>
				<region>ONTARIO</region>
				<country>Canada</country>
			</address>
		</defaultuser>
	</defaults>
</inputdata>
